terraform-aws-modules/terraform-aws-autoscaling

main.tf
modules/autoscaling_group/main.tf

Fix for:
```
module.bastion.module.autoscaling_group.aws_autoscaling_group.this: target_group_arns: should be a list
```

Fix passing list from main to ASG for target_group_arns

---

variables.tf

It's not the same as other AWS resources.

Describe tag format

---

main.tf

- add supplied tag blocks after name block so that all of the tags don't get rearranged every time one is added or removed.
- remove unneeded concat of var.launch_configuration into the launch_config name

Launch configuration naming, tagging fix/clarity

---

README.md
locals.tf
main.tf
outputs.tf
variables.tf

added support for up to 10 custom tags in the same format as all other aws resources by using interpolation in local variables that split and rejoin in appropriate format.
This requires alot more code then it should, but due to Terraform being declarative and not having iterators on non-resource objects we inevitably need some repetition.  Would love to hear what you think about this addition.  Should not interfere with existing configurations but does allow for an additional variable that concats with the existing tags variable in main.tf.  Passes my local testing.

ref #12 #1 - resolve tagging format difference

---

main.tf
variables.tf

`spot_price` does not work with `placement_tenancy`.
But if you set `spot_price` or `placement_tenancy` individually, it do work.
By specifying `spot_price` to `""` by default, it act as no spot price so
you can set `placement_tenancy` to `dedicated`.
Using the ternary for `placement_tenancy`, it allows to specify `spot_price`
and leave `placement_tenancy` to the default value.

Enable spot_price on launch configuration

---

examples/asg_elb/main.tf

```
The given value is not suitable for child module variable "health_check"
defined at .terraform/modules/elb/terraform-aws-modules-terraform-aws-elb-63ebc39/variables.tf:69,1-24: map of string required.
```

Fixed example (health_check to map of strings)

---

main.tf

The `root_block_device` block in `aws_launch_configuration` supports an `encrypted` parameter. This parameter was missing in the dynamic block in the module. 
https://www.terraform.io/docs/providers/aws/r/launch_configuration.html#root_block_device

add `encrypted` option to root_block_device

---

README.md
main.tf
variables.tf

Adds IAM service_linked_role for ASG to call EBS encryption(KMS), S3 or any other AWS services. Creating IAM role should be out of scope of this module, thus, making it a variable. Closes #63

Adds service_linked_role

---

README.md
main.tf
variables.tf
versions.tf

I've added missed [max_instance_lifetime](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#max_instance_lifetime) option for Auto Scaling Group.

feat: Added max_instance_lifetime option for Auto Scaling Group

---

README.md
examples/asg_ec2/README.md
examples/asg_ec2_external_launch_configuration/README.md
examples/asg_elb/README.md
examples/asg_inital_lifecycle_hook/README.md
versions.tf

Bumping aws-provider requirement to ">= 2.41, < 4.0"
Bumping terraform requirement to ">= 0.12.6, < 0.14"
There is newer terraform and provider version available.
As stated [here](https://github.com/terraform-providers/terraform-provider-aws/releases/tag/v3.0.0)
Run it locally on aws 2.41, aws 2.7, aws 3.0 and aws 3.1

feat: aws-provider version bump to >= 2.41, < 4.0

---

main.tf

Add support for custom kms key for ebs and root block
Actually it is not possible to use custom kms key

feat: add support for "kms_key_id" property in "ebs_block_device" and "root_block_device"

---

.pre-commit-config.yaml
examples/asg_ec2/main.tf
locals.tf
main.tf

- convert tags to dynamic tags to allow for empty values. this is the workaround solution described here https://github.com/terraform-providers/terraform-provider-aws/issues/9049
- update pre-commit hooks to latest 
- Closes #102
No
`asg_ec2` example has been updated to include the empty tags and when deployed it works as expected

fix: convert to dynamic tags to allow for empty values

---

.gitignore
.pre-commit-config.yaml
README.md
examples/asg_ec2/README.md
examples/asg_ec2_external_launch_configuration/README.md
examples/asg_elb/README.md
examples/asg_inital_lifecycle_hook/README.md

- update documentation based on latest `terraform-docs` which includes module and resource sections
- `.gitignore` updated using GitHub provided default standard + 0.14 lockfile ignore
- these are two new sections provided by [`terraform-docs` now](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.11.0)
No
N/A

chore: update documentation based on latest `terraform-docs` which includes module and resource sections

---

.github/workflows/pre-commit.yml

- only run validate check on min terraform version
- validate will run on both min and max supported terraform versions, but format, lint, and docs will only run on max/latest version of terraform supported
- no
- static check github action

chore: only run validate check on min terraform version

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
README.md
examples/asg_ec2/README.md
examples/asg_ec2_external_launch_configuration/README.md
examples/asg_elb/README.md
examples/asg_inital_lifecycle_hook/README.md

- align ci-cd static checks to use individual minimum Terraform versions
- ensure that the modules are all following a similar workflow and the static checks that performed
- No
- ci-cd static checks

chore: align ci-cd static checks to use individual minimum Terraform versions

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml
README.md
examples/asg_ec2/README.md
examples/asg_ec2/versions.tf
examples/asg_ec2_external_launch_configuration/README.md
examples/asg_ec2_external_launch_configuration/versions.tf
examples/asg_elb/README.md
examples/asg_elb/versions.tf
examples/asg_inital_lifecycle_hook/README.md
examples/asg_inital_lifecycle_hook/versions.tf
versions.tf

- update documentation and pin `terraform_docs` version to avoid future changes
- bump minimum version of terraform due to ci/cd failure
- pin version to avoid unnecessary updates when a PR coincides with a version update for `terraform_docs`
- no
- documentation change only - ci/cd should pass checks

chore: update documentation and pin `terraform_docs` version to avoid future changes

---

main.tf

- add tags to launch template
- tags attribute was overlooked for launch template resource and tags were not added
Closes #140
- No

fix: add tags to launch template

---

README.md
examples/complete/README.md
examples/complete/main.tf
examples/complete/versions.tf
main.tf
variables.tf

Adds support for `aws_autoscaling_group`'s `warm_pool` configuration.
This isn't a hill I need to die on. If this change is risky for some reason that's non-obvious to me, we can forego a merge of this.
This is a relatively new feature to the underlying `aws` provider: https://github.com/hashicorp/terraform-provider-aws/pull/18734
See supplied example.

feat: Add support for `warm_pool`

---

.pre-commit-config.yaml
README.md
variables.tf

- when Maximum instance lifetime was [announced](https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-ec2-auto-scaling-supports-max-instance-lifetime/) the minimum TTL was set to 7 days. 
- After that the value changed to 1 day  and the [user guide](https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-max-instance-lifetime.html) was updated. 
- This will ensure the docs matches the documentation.
- This ensures the description of the variable matches the supported values.
N/A
N/A

docs: Fixed max_instance_lifetime min value in description

---

README.md
examples/complete/main.tf
main.tf
versions.tf

checkpoint_delay - (Optional) The number of seconds to wait after a checkpoint. Defaults to 3600.
checkpoint_percentages - (Optional) List of percentages for each checkpoint. Values must be unique and in ascending order. To replace all instances, the final number must be 100.
Parameter docs:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#preferences
- I have tested and validated these changes using one or more of the provided `examples/*` projects, triggered instance refresh by editing a tag and redeploying

feat: add checkpoint_delay, checkpoint_percent to instance refresh

---

README.md
examples/complete/README.md
examples/complete/main.tf
examples/complete/versions.tf
main.tf
versions.tf

- add `instance_metadata_tags` attribute to launch template (launch config not supported, no longer receiving updates) and bump AWS provider to support
- AWS now allows users to attach/query tags via the metadata endpoint service
- No
- `complete` example

feat: Add `instance_metadata_tags` attribute to launch temlplate and bump AWS provider to support

---

README.md
examples/complete/README.md
examples/complete/main.tf
examples/complete/outputs.tf
main.tf
outputs.tf
variables.tf

This PR adds support for aws_autoscaling_policy resource
Support is fully complete and covers all settings mentioned in documentation(https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_policy)
I decided to implement support for this resource, as it's a part of ASGs, brings (important in my opinion) feature to scale-in / scale out based on CPU load metric (predefined_metric_type = ASGAverageCPUUtilization)
- [ *] I have tested and validated these changes using one or more of the provided `examples/*` projects
I tested this PR creating ASG with addition of following block of code:
```
create_scaling_policy = true
scaling_policies = {
was-avg-cpu-policy-greater-than-xx = {
policy_type               = "TargetTrackingScaling"
estimated_instance_warmup = …
```

feat: Add support for aws_autoscaling_policy

---

main.tf

- Update syntax to be more concise using `try()` to replace verbose lookups to see if a value is provided or not
- Continuation of convo here https://github.com/terraform-aws-modules/terraform-aws-autoscaling/pull/173#discussion_r805824919
- No
- Tested with `complete` example and this change is a no-op compared against `master`

fix: Update syntax to be more concise using `try()` to replace verbose lookups to see if a value is provided or not

---

README.md

Example is either outdated or wrong
variables.tf has
```terraform
variable "tags" {
description = "A map of tags to assign to resources"
type        = map(string)
default     = {}
}
```
there is no tags_as_map.
Let's adjust this info
No breaking changes
no tests required

chore: Fixed tags in readme

---

.pre-commit-config.yaml
README.md
examples/complete/README.md
examples/complete/main.tf
examples/complete/versions.tf
main.tf
variables.tf
versions.tf

- Update provider to `v4.x` to support attributes added
- Change `user_data_base64` to `user_data` to match resource name used
- Add `capacity_reservation_resource_group_arn` attribute to `capacity_reservation_specification.capacity_reservation_target`
- Add `ipv4_prefix_count`, `ipv4_prefixes`, `ipv6_prefix_count`, `ipv6_prefixes` to `network_interfaces`
- Add `private_dns_name_options` block and its attributes
- Add `instance_reuse_policy` block and its attributes to `warm_pool`
- Updates module to use latest features offered in `v4.x` provider
- Variable name change made to align with resource name spec (was a legacy name that looks to have been missed in prior breaking change)
- Pulling this module up to be as current as possible before using in EKS module v19.x
- This module will …

feat!: Update provider to `v4.x`, add new attributes from `v4.x`, change `user_data_base64` to `user_data`

---

examples/complete/README.md
examples/complete/main.tf
main.tf

- Improved support for EFA network interfaces. Do to https://github.com/hashicorp/terraform-provider-aws/issues/4570, users cannot specify both `var.security_groups` and `var.network_interfaces`. Therefore, to make this issue seamless to users, when one or more network interface definition is provided, the `var.security_groups` are transparently moved down to the interface. Users can still provide additional security groups per interface if they desire
- Relates to change made here https://github.com/terraform-aws-modules/terraform-aws-eks/pull/1980
- No
- Added a beefy, expensive example in `examples/complete`

feat: Improved support for EFA network interfaces

---

README.md
main.tf
variables.tf

- Correct variable name for `availability_zones` to match resource spec and denote that its more than one item
- Add new, separate variable for `autoscaling_group_tags` to add tags to just the autoscaling group
- Looks like a typo - should have had the trailing `s`
- No

feat: Add separate autoscaling group tag variable, correct variable name for `availability_zones` to match resource spec

---

README.md
examples/complete/README.md
examples/complete/outputs.tf
outputs.tf

- Add outputs for launch template name and default version
- Commonly used attributes used by downstream components when using launch templates only (no ASG created)
- No

feat: Add outputs for launch template name and default version

---

.pre-commit-config.yaml
README.md
examples/complete/README.md
examples/complete/main.tf
examples/complete/outputs.tf
examples/complete/versions.tf
main.tf
outputs.tf
variables.tf
versions.tf

- Add support for autoscaling group `maintenance_options`
- Add support launch template `instance_requirements`. This works as intended for the launch template, but additional provider updates are needed for this to integrate and work with autoscaling group https://github.com/hashicorp/terraform-provider-aws/issues/21566
- Adding support for attribute based instance selection
- No

feat: Add support for ASG `maintenance_options` and LT `instance_requirements`

---

README.md
examples/complete/main.tf
variables.tf

The variable `warm_pool` should support strings, numbers and other maps. 
Fixes #201.
No

fix: Correct type constraint of `warm_pool` variable

---

README.md
examples/complete/README.md
examples/complete/versions.tf
main.tf
variables.tf
versions.tf

This PR implements the feature request #217 
This PR allows to disable_api_stop at the launch template level.
No

feat: Add support for `disable_api_stop`

---

README.md
examples/complete/README.md
examples/complete/main.tf
examples/complete/versions.tf
main.tf
variables.tf
versions.tf

- `launch_template_id` is used in place of `launch_template_name`. If using an external launch template, you will need to now pass a `launch_template_id` instead of `launch_template_name`
- Minimum supported version of AWS provider raised to `v5.0` and Terraform raised to `v1.0`
- Previously `scaling_policies` `step_adjustment` argument accepted a single map and has since changed to accept multiple maps of scaling step adjustments
In case the value of `launch_template_name` changes, a new launch template will be created but the auto scaling group still points to the old launch template. 
If you execute `terraform apply` a second time, the auto scaling group tries to change the name of the launch template, but keeps the id of the old launch template which is not valid anymore. 
Using the …

feat!: Use `launch_template_id` instead of `launch_template_name`, raise MSV of AWS provider and Terraform to 5.0 and 1.0 respectively

---

README.md
examples/complete/README.md
examples/complete/main.tf
examples/complete/versions.tf
main.tf
variables.tf
versions.tf

Add `scale_in_protected_instances` and `standby_instances` to `aws_autoscaling_group` `instance_refresh.preferences`. 
Add `ignore_failed_scaling_activities`. 
Min provider version `5.16.2` based on https://github.com/hashicorp/terraform-provider-aws/pull/33382
Additional `instance_refresh.preferences`: https://github.com/hashicorp/terraform-provider-aws/pull/33310
`ignore_failed_scaling_activities`: https://github.com/hashicorp/terraform-provider-aws/pull/32914
No.

feat: Instance refresh preferences

---

README.md

set hops to 1 as per aws recommendation
https://docs.aws.amazon.com/securityhub/latest/userguide/autoscaling-controls.html#autoscaling-4
Follow best practices
None

docs: Update README to restrict max hop limit for IMDSv2

---

.pre-commit-config.yaml
main.tf

- Ignore changes to `load_balancers` and `target_group_arns`
- Ref https://github.com/hashicorp/terraform-provider-aws/issues/14540
- Resolves #250
- No

fix: Ignore changes to `load_balancers` and `target_group_arns`

---

README.md
examples/complete/README.md
examples/complete/main.tf
examples/complete/versions.tf
main.tf
versions.tf

The [aws_launch_template](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template) resource supports an `allowed_instance_types` field in the `instance_requirements` block.
> [allowed_instance_types](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#allowed_instance_types) - (Optional) List of instance types to apply your specified attributes against. All other instance types are ignored, even if they match your specified attributes. You can use strings with one or more wild cards, represented by an asterisk (*), to allow an instance type, size, or generation. The following are examples: m5.8xlarge, c5*.*, m5a.*, r*, *3*. For example, if you specify c5*, you are allowing the entire C5 instance family, which …

feat: Add `allowed_instance_types` to `instance_requirements`

---

README.md
examples/complete/README.md
examples/complete/main.tf
examples/complete/versions.tf
main.tf
versions.tf

Support alarm specification in instance refresh preferences. 
https://github.com/hashicorp/terraform-provider-aws/pull/36954
No.

feat: Support Alarm Specification in Instance Refresh Preferences

---

README.md
examples/complete/README.md
examples/complete/versions.tf
main.tf
variables.tf
versions.tf

Support `aws_autoscaling_group.availability_zone_distribution`. 
- https://github.com/hashicorp/terraform-provider-aws/pull/40634
No.

feat: Support `aws_autoscaling_group.availability_zone_distribution`

---

main.tf

Support aws_launch_template.network_interfaces.primary_ipv6
https://github.com/hashicorp/terraform-provider-aws/pull/37142
No

feat: Add support for `primary_ipv6` in launch template

---

README.md
examples/complete/README.md
examples/complete/main.tf
examples/complete/versions.tf
main.tf
variables.tf
versions.tf

Support launch template `network_interfaces.connection_tracking_specification`. 
Support Autoscaling policy `metric_stat.period`. 
- https://github.com/hashicorp/terraform-provider-aws/pull/41066
- https://github.com/hashicorp/terraform-provider-aws/pull/41184
No.

feat: Support Launch Template `network_interfaces.connection_tracking_specification` and Autoscaling Policy `metric_stat.period`

---

.pre-commit-config.yaml
README.md
examples/complete/README.md
examples/complete/versions.tf
versions.tf
wrappers/versions.tf

- Restrict AWS provider version from using `v6.x` which contains breaking changes
- Closes #290
- No

fix: Restrict AWS provider version from using `v6.x` which contains breaking changes

---

main.tf

- Correct null check between two definitions of ASG
```
│ Error: Invalid dynamic for_each value
│
│   on .terraform/modules/autoscaling/main.tf line 373, in resource "aws_autoscaling_group" "idc":
│  373:     for_each = var.initial_lifecycle_hooks
│     ├────────────────
│     │ var.initial_lifecycle_hooks is null
│
│ Cannot use a null value in for_each.
╵
```
- No

fix: Correct null check between two definitions of ASG
